# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
tone_instructions: >-
  Expert PHP code reviewer. Focus on type safety, PSR-12, PHP 8.2-8.5
  compatibility, and security. PHP 8.0+ features (named arguments, match,
  constructor promotion, nullsafe operator) are allowed.

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "htdocs/**/*.php"
      instructions: >-
        Review for PHP 8.2-8.5 compatibility. PHP 8.0 features (union types,
        named arguments, match expressions, constructor promotion, nullsafe
        operator) are allowed. PHP 8.1 features (enums, readonly properties,
        intersection types, fibers, first-class callable syntax) are allowed.
        PHP 8.2 features (readonly classes, DNF types, standalone true/false/null
        types, constants in traits) are allowed. Avoid PHP 8.3+ features.
        Check for proper PSR-12 code style. Flag any direct superglobal access
        ($_GET, $_POST, $_REQUEST) that should use Xmf\Request instead.
        Check for SQL injection risks — all queries must use parameterized
        statements via XOOPS database handlers.
    - path: "htdocs/kernel/**/*.php"
      instructions: >-
        Core kernel classes. Pay special attention to security: input
        filtering, output escaping, SQL parameterization, and proper
        use of XOOPS database API. Check for backward compatibility.
    - path: "tests/**/*.php"
      instructions: >-
        Review test code for proper assertions, test isolation, and edge
        case coverage. Tests must work across PHPUnit 9.6, 10, and 11.
  tools:
    phpcs:
      enabled: true
    phpstan:
      enabled: true
    gitleaks:
      enabled: true
    markdownlint:
      enabled: true
    yamllint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000

chat:
  auto_reply: true
