<?php
/*
 * XOOPS Menu Items Kernel Object
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * @copyright    2000-2026 XOOPS Project https://xoops.org/
 * @license      GNU GPL 2.0 or later (https://www.gnu.org/licenses/gpl-2.0.html)
 * @since        2.5.12
 * @author       XOOPS Development Team
 */

defined('XOOPS_ROOT_PATH') || exit('Restricted access');

/**
 * A single menu item within a category.
 */
class XoopsMenusItems extends XoopsObject
{
    /** @var bool Whether the language file has been loaded */
    private static bool $langLoaded = false;

    public function __construct()
    {
        parent::__construct();
        $this->initVar('items_id', XOBJ_DTYPE_INT, null, false);
        $this->initVar('items_pid', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('items_cid', XOBJ_DTYPE_INT, 0, true);
        $this->initVar('items_title', XOBJ_DTYPE_TXTBOX, '', true, 100);
        $this->initVar('items_prefix', XOBJ_DTYPE_TXTAREA, '', false);
        $this->initVar('items_suffix', XOBJ_DTYPE_TXTAREA, '', false);
        $this->initVar('items_url', XOBJ_DTYPE_TXTBOX, '', false, 255);
        $this->initVar('items_target', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('items_position', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('items_protected', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('items_active', XOBJ_DTYPE_INT, 1, false);
    }

    /**
     * Return the database id generated by the most recent insert.
     *
     * The admin controller uses this helper after a successful item save
     * when it needs the persisted primary key for permissions or redirects.
     *
     * @return int Newly created menu item id
     */
    public function getNewEnreg(): int
    {
        return (int) \XoopsDatabaseFactory::getDatabaseConnection()->getInsertId();
    }

    /**
     * Load menu language files if not already loaded.
     *
     * Uses the standard xoops_loadLanguage() helper, which automatically
     * falls back to English when a translation is not available.
     */
    private static function ensureLanguageLoaded(): void
    {
        if (self::$langLoaded) {
            return;
        }
        xoops_loadLanguage('menus/menus', 'system');
        xoops_loadLanguage('admin/menus', 'system');
        self::$langLoaded = true;
    }

    /**
     * Retrieve the resolved title for display.
     *
     * If the stored title is a language constant name, resolves and returns
     * its translated value. Otherwise returns the stored title as-is. This
     * is the value used when rendering menu items on the front end.
     *
     * @return string The resolved title value
     */
    public function getResolvedTitle(): string
    {
        self::ensureLanguageLoaded();
        $raw = $this->getVar('items_title', 'n');
        if ($raw !== '' && defined($raw)) {
            return constant($raw);
        }
        return (string) $raw;
    }

    /**
     * Retrieve the title for the administration interface.
     *
     * When a menu item title is backed by a language constant, the admin view
     * keeps the original token visible beside the translated value so it is
     * easier to manage seeded entries and translations.
     *
     * @return string The resolved title with an optional constant reference
     */
    public function getAdminTitle(): string
    {
        $raw      = (string) $this->getVar('items_title', 'n');
        $resolved = $this->getResolvedTitle();
        if ($resolved !== $raw) {
            return $resolved . ' (' . $raw . ')';
        }
        return $resolved;
    }

    /**
     * Build and return the item create/edit form.
     *
     * The form is category-aware: it validates the owning category, limits
     * the parent selector to active items in the same category, preserves
     * raw affix values for later sanitization, and exposes the matching
     * permission selector used by the admin controller.
     *
     * @param int    $categoryId Category id that owns the item
     * @param string $action     Form action URL
     *
     * @return \XoopsThemeForm
     */
    public function getFormItems(int $categoryId, string $action): \XoopsThemeForm
    {
        include_once XOOPS_ROOT_PATH . '/class/xoopsformloader.php';
        include_once XOOPS_ROOT_PATH . '/class/xoopsform/grouppermform.php';

        $isEdit      = (bool) $this->getVar('items_id');
        $isProtected = (bool) $this->getVar('items_protected');
        $title       = $isEdit ? _AM_SYSTEM_MENUS_EDITITEM : _AM_SYSTEM_MENUS_ADDITEM;

        $form = new \XoopsThemeForm($title, 'itemform', $action, 'post', true);

        if ($isEdit) {
            $form->addElement(new \XoopsFormHidden('items_id', (string) $this->getVar('items_id')));
        }
        $form->addElement(new \XoopsFormHidden('items_cid', (string) $categoryId));

        $catHandler = xoops_getHandler('menuscategory');
        $catObj     = $catHandler->get($categoryId);
        if ($catObj) {
            $form->addElement(new \XoopsFormLabel(
                _AM_SYSTEM_MENUS_ITEMCATEGORY,
                htmlspecialchars($catObj->getAdminTitle(), ENT_QUOTES, 'UTF-8')
            ));
        }

        $form->addElement($this->buildParentSelector($categoryId, $isProtected));

        $titleField = new \XoopsFormText(
            _AM_SYSTEM_MENUS_ITEMTITLE,
            'items_title',
            60,
            100,
            $this->getVar('items_title', 'e')
        );
        $titleField->setDescription(_AM_SYSTEM_MENUS_ITEMTITLE_DESC);
        if ($isProtected) {
            $titleField->setExtra('readonly="readonly"');
        }
        $form->addElement($titleField, true);

        $prefixField = $this->buildAffixField('items_prefix', _AM_SYSTEM_MENUS_ITEMPREFIX, $isProtected);
        $prefixField->setDescription(_AM_SYSTEM_MENUS_ITEMPREFIX_DESC);
        $form->addElement($prefixField);

        $suffixField = $this->buildAffixField('items_suffix', _AM_SYSTEM_MENUS_ITEMSUFFIX, $isProtected);
        $suffixField->setDescription(_AM_SYSTEM_MENUS_ITEMSUFFIX_DESC);
        $form->addElement($suffixField);

        $urlField = new \XoopsFormText(
            _AM_SYSTEM_MENUS_ITEMURL,
            'items_url',
            60,
            255,
            $this->getVar('items_url', 'e')
        );
        if ($isProtected) {
            $urlField->setExtra('readonly="readonly"');
        }
        $form->addElement($urlField);

        $targetField = new \XoopsFormRadio(
            _AM_SYSTEM_MENUS_ITEMTARGET,
            'items_target',
            (string) $this->getVar('items_target')
        );
        $targetField->addOption('0', _AM_SYSTEM_MENUS_TARGET_SELF);
        $targetField->addOption('1', _AM_SYSTEM_MENUS_TARGET_BLANK);
        $form->addElement($targetField);

        $form->addElement(new \XoopsFormText(
            _AM_SYSTEM_MENUS_ITEMPOSITION,
            'items_position',
            5,
            10,
            (string) $this->getVar('items_position')
        ));
        $form->addElement(new \XoopsFormRadioYN(
            _AM_SYSTEM_MENUS_ACTIVE,
            'items_active',
            (int) $this->getVar('items_active')
        ));

        $permField = new \XoopsGroupPermForm('', $GLOBALS['xoopsModule']->getVar('mid'), 'menus_items_view', '');
        $permField->addItem((int) $this->getVar('items_id'), _AM_SYSTEM_MENUS_PERMISSION_VIEW_ITEM);
        $form->addElement($permField);

        $form->addElement(new \XoopsFormHidden('op', 'saveitem'));
        $form->addElement(new \XoopsFormButton('', 'submit', _SUBMIT, 'submit'));

        return $form;
    }

    /**
     * Build a parent-item dropdown for the given category.
     *
     * @param int  $categoryId  The category to list items from
     * @param bool $isProtected Whether the selector should be disabled
     *
     * @return \XoopsFormSelect
     */
    private function buildParentSelector(int $categoryId, bool $isProtected): \XoopsFormSelect
    {
        $currentId = (int) $this->getVar('items_id');
        $handler   = xoops_getHandler('menusitems');
        $criteria  = new \CriteriaCompo(new \Criteria('items_cid', (string) $categoryId));
        $criteria->setSort('items_position');
        $criteria->setOrder('ASC');
        $allItems = $handler->getObjects($criteria);

        $options = [0 => '---'];
        foreach ($allItems as $sibling) {
            $sid = (int) $sibling->getVar('items_id');
            if ($sid !== $currentId) {
                $options[$sid] = $sibling->getAdminTitle();
            }
        }

        $field = new \XoopsFormSelect(
            _AM_SYSTEM_MENUS_ITEMPARENT,
            'items_pid',
            (string) $this->getVar('items_pid'),
            1,
            false
        );
        $field->addOptionArray($options);
        if ($isProtected) {
            $field->setExtra('disabled="disabled"');
        }
        return $field;
    }

    /**
     * Build a textarea element for a prefix/suffix affix field.
     *
     * Affix values are stored raw so the front-end renderer can sanitize
     * and expand placeholders like `<{xoInboxCount}>` at output time.
     *
     * @param string $varName     The variable name
     * @param string $label       The form label
     * @param bool   $isProtected Whether the field should be readonly
     *
     * @return \XoopsFormTextArea
     */
    private function buildAffixField(string $varName, string $label, bool $isProtected): \XoopsFormTextArea
    {
        $value = (string) $this->getVar($varName, 'n');
        $field   = new \XoopsFormTextArea($label, $varName, $value, 3, 60);
        if ($isProtected) {
            $field->setExtra('readonly="readonly"');
        }
        return $field;
    }
}

/**
 * Handler for XoopsMenusItems objects.
 *
 * Note: Constructor accepts \XoopsDatabase to match parent XoopsPersistableObjectHandler
 * signature. At runtime, the concrete XoopsMySQLDatabase is always passed.
 */
class XoopsMenusItemsHandler extends \XoopsPersistableObjectHandler
{
    /**
     * @param \XoopsDatabase $db Database connection
     */
    public function __construct(\XoopsDatabase $db)
    {
        parent::__construct($db, 'menusitems', 'XoopsMenusItems', 'items_id', 'items_title');
    }

    /**
     * Fetch active items from a set of allowed IDs, sorted by position.
     *
     * Used by the theme loader after permission filtering to retrieve
     * only the items visible to the current user.
     *
     * @param int[] $itemIds Item IDs the current user may see
     *
     * @return array<int, XoopsMenusItems>
     */
    public function getActiveItemsByIds(array $itemIds): array
    {
        $itemIds = array_values(array_filter(array_map('intval', $itemIds)));
        if ([] === $itemIds) {
            return [];
        }

        $criteria = new \CriteriaCompo();
        $criteria->add(new \Criteria('items_active', '1'));
        $criteria->add(new \Criteria('items_id', $itemIds, 'IN'));
        $criteria->setSort('items_position');
        $criteria->setOrder('ASC');

        return $this->getAll($criteria);
    }

    /**
     * Fetch all active items belonging to a single category, sorted by position.
     *
     * @param int $categoryId The parent category ID
     *
     * @return array<int, XoopsMenusItems>
     */
    public function getActiveItemsByCategory(int $categoryId): array
    {
        $criteria = new \CriteriaCompo();
        $criteria->add(new \Criteria('items_active', '1'));
        $criteria->add(new \Criteria('items_cid', (string) $categoryId));
        $criteria->setSort('items_position');
        $criteria->setOrder('ASC');

        return $this->getAll($criteria);
    }
}
