<?php
/*
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * XOOPS Menu Category Kernel Object
 * @copyright    2000-2026 XOOPS Project https://xoops.org/
 * @license      GNU GPL 2.0 or later (https://www.gnu.org/licenses/gpl-2.0.html)
 * @since        2.5.12
 * @author       XOOPS Development Team
 */

defined('XOOPS_ROOT_PATH') || exit('Restricted access');

/**
 * A single menu category (top-level navigation group).
 */
class XoopsMenusCategory extends XoopsObject
{
    /** @var bool Whether the language file has been loaded */
    private static bool $langLoaded = false;

    public function __construct()
    {
        parent::__construct();
        $this->initVar('category_id', XOBJ_DTYPE_INT, null, false);
        $this->initVar('category_title', XOBJ_DTYPE_TXTBOX, '', true, 100);
        $this->initVar('category_prefix', XOBJ_DTYPE_TXTAREA, '', false);
        $this->initVar('category_suffix', XOBJ_DTYPE_TXTAREA, '', false);
        $this->initVar('category_url', XOBJ_DTYPE_TXTBOX, '', false, 255);
        $this->initVar('category_target', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('category_position', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('category_protected', XOBJ_DTYPE_INT, 0, false);
        $this->initVar('category_active', XOBJ_DTYPE_INT, 1, false);
    }

    /**
     * Return the database id generated by the most recent insert.
     *
     * XOOPS historically exposes this helper on persistable objects so the
     * admin controller can read back the primary key after a successful save.
     *
     * @return int Newly created category id
     */
    public function getNewEnreg(): int
    {
        return (int) \XoopsDatabaseFactory::getDatabaseConnection()->getInsertId();
    }

    /**
     * Load menu language files if not already loaded.
     *
     * Uses the standard xoops_loadLanguage() helper, which automatically
     * falls back to English when a translation is not available.
     */
    private static function ensureLanguageLoaded(): void
    {
        if (self::$langLoaded) {
            return;
        }
        xoops_loadLanguage('menus/menus', 'system');
        xoops_loadLanguage('admin/menus', 'system');
        self::$langLoaded = true;
    }

    /**
     * Retrieve the resolved title for display.
     *
     * If the stored title is a language constant name, resolves and returns
     * its translated value. Otherwise returns the stored title as-is. Used
     * for front-end rendering where the translated label should be shown
     * without the raw constant token.
     *
     * @return string The resolved title value
     */
    public function getResolvedTitle(): string
    {
        self::ensureLanguageLoaded();
        $raw = $this->getVar('category_title', 'n');
        if ($raw !== '' && defined($raw)) {
            return constant($raw);
        }
        return (string) $raw;
    }

    /**
     * Retrieve the title for the administration interface.
     *
     * When the stored value is a language constant, the admin view shows both
     * the translated label and the original constant token so maintainers can
     * identify which language constant is backing each menu entry.
     *
     * @return string The resolved title with an optional constant reference
     */
    public function getAdminTitle(): string
    {
        $raw      = (string) $this->getVar('category_title', 'n');
        $resolved = $this->getResolvedTitle();
        if ($resolved !== $raw) {
            return $resolved . ' (' . $raw . ')';
        }
        return $resolved;
    }

    /**
     * Build and return the category create/edit form.
     *
     * The form covers title, prefix/suffix affixes, URL, target, ordering,
     * active state, and group permissions. Protected seeded categories remain
     * editable only where it is safe to do so — core fields are locked while
     * position and active state remain adjustable.
     *
     * @param string $action Form action URL
     *
     * @return \XoopsThemeForm
     */
    public function getFormCat(string $action): \XoopsThemeForm
    {
        include_once XOOPS_ROOT_PATH . '/class/xoopsformloader.php';

        $isEdit      = (bool) $this->getVar('category_id');
        $isProtected = (bool) $this->getVar('category_protected');
        $title       = $isEdit ? _AM_SYSTEM_MENUS_EDITCAT : _AM_SYSTEM_MENUS_ADDCAT;

        $form = new \XoopsThemeForm($title, 'categoryform', $action, 'post', true);

        if ($isEdit) {
            $form->addElement(new \XoopsFormHidden('category_id', (string) $this->getVar('category_id')));
        }

        $titleField = new \XoopsFormText(
            _AM_SYSTEM_MENUS_CATTITLE,
            'category_title',
            60,
            100,
            (string) $this->getVar('category_title', 'e')
        );
        $titleField->setDescription(_AM_SYSTEM_MENUS_CATTITLE_DESC);
        if ($isProtected) {
            $titleField->setExtra('readonly="readonly"');
        }
        $form->addElement($titleField, true);

        $prefixField = $this->buildAffixField('category_prefix', _AM_SYSTEM_MENUS_CATPREFIX, $isProtected);
        $prefixField->setDescription(_AM_SYSTEM_MENUS_CATPREFIX_DESC);
        $form->addElement($prefixField);

        $suffixField = $this->buildAffixField('category_suffix', _AM_SYSTEM_MENUS_CATSUFFIX, $isProtected);
        $suffixField->setDescription(_AM_SYSTEM_MENUS_CATSUFFIX_DESC);
        $form->addElement($suffixField);

        $urlField = new \XoopsFormText(
            _AM_SYSTEM_MENUS_CATURL,
            'category_url',
            60,
            255,
            $this->getVar('category_url', 'e')
        );
        $urlField->setDescription(_AM_SYSTEM_MENUS_CATURL_DESC);
        if ($isProtected) {
            $urlField->setExtra('readonly="readonly"');
        }
        $form->addElement($urlField);

        $targetField = new \XoopsFormRadio(
            _AM_SYSTEM_MENUS_CATTARGET,
            'category_target',
            (string) $this->getVar('category_target')
        );
        $targetField->addOption('0', _AM_SYSTEM_MENUS_TARGET_SELF);
        $targetField->addOption('1', _AM_SYSTEM_MENUS_TARGET_BLANK);
        $form->addElement($targetField);

        $form->addElement(new \XoopsFormText(
            _AM_SYSTEM_MENUS_CATPOSITION,
            'category_position',
            5,
            10,
            (string) $this->getVar('category_position')
        ));
        $form->addElement(new \XoopsFormRadioYN(
            _AM_SYSTEM_MENUS_ACTIVE,
            'category_active',
            (int) $this->getVar('category_active')
        ));

        $permHelper = new \Xmf\Module\Helper\Permission();
        $permField = $permHelper->getGroupSelectFormForItem(
            'menus_category_view',
            (int) $this->getVar('category_id'),
            _AM_SYSTEM_MENUS_PERMISSION_VIEW_CATEGORY,
            'menus_category_view_perms',
            true
        );
        $form->addElement($permField, false);

        $form->addElement(new \XoopsFormHidden('op', 'savecat'));
        $form->addElement(new \XoopsFormButton('', 'submit', _SUBMIT, 'submit'));

        return $form;
    }

    /**
     * Build a textarea element for a prefix/suffix affix field.
     *
     * Affix values are stored raw so the front-end renderer can sanitize
     * and expand placeholders like `<{xoInboxCount}>` at output time.
     *
     * @param string $varName     The variable name
     * @param string $label       The form label
     * @param bool   $isProtected Whether the field should be readonly
     *
     * @return \XoopsFormTextArea
     */
    private function buildAffixField(string $varName, string $label, bool $isProtected): \XoopsFormTextArea
    {
        $value = (string) $this->getVar($varName, 'n');
        $field   = new \XoopsFormTextArea($label, $varName, $value, 3, 60);
        if ($isProtected) {
            $field->setExtra('readonly="readonly"');
        }
        return $field;
    }
}

/**
 * Handler for XoopsMenusCategory objects.
 *
 * Note: Constructor accepts \XoopsDatabase to match parent XoopsPersistableObjectHandler
 * signature. At runtime, the concrete XoopsMySQLDatabase is always passed.
 */
class XoopsMenusCategoryHandler extends \XoopsPersistableObjectHandler
{
    /**
     * @param \XoopsDatabase $db Database connection
     */
    public function __construct(\XoopsDatabase $db)
    {
        parent::__construct($db, 'menuscategory', 'XoopsMenusCategory', 'category_id', 'category_title');
    }

    /**
     * Fetch active categories from a set of allowed IDs, sorted by position.
     *
     * Used by the theme loader after permission filtering to retrieve
     * only the categories visible to the current user.
     *
     * @param int[] $categoryIds Category IDs the current user may see
     *
     * @return array<int, XoopsMenusCategory>
     */
    public function getActiveCategoriesByIds(array $categoryIds): array
    {
        $categoryIds = array_values(array_filter(array_map('intval', $categoryIds)));
        if ([] === $categoryIds) {
            return [];
        }

        $criteria = new \CriteriaCompo();
        $criteria->add(new \Criteria('category_active', '1'));
        $criteria->add(new \Criteria('category_id', $categoryIds, 'IN'));
        $criteria->setSort('category_position');
        $criteria->setOrder('ASC');

        return $this->getAll($criteria);
    }
}
