# language: php
build:
  environment:
    php: 8.1.0
  nodes:
    tests: true
    analysis:
      dependencies:
        after:
        # The following installs the most recent XOOPS CMS version, you might want
        # to install a specific release tag or branch instead.
        - git clone --depth=1 https://github.com/XOOPS/XoopsCore25
        - git clone --depth=1 https://github.com/mambax7/tag
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
filter:
  dependency_paths:
    - XoopsCore25/*
    - tag/*

