/**
 */

tinyMCE.addI18n('en.xoopsimagemanager_dlg',{
    tab_general:"General",
    tab_appearance:"Appearance",
    tab_advanced:"Advanced",
    general:"General",
    title:"Title",
    preview:"Preview",
    constrain_proportions:"Constrain proportions",
    langdir:"Language direction",
    langcode:"Language code",
    long_desc:"Long description link",
    style:"Style",
    classes:"Classes",
    ltr:"Left to right",
    rtl:"Right to left",
    id:"Id",
    map:"Image map",
    swap_image:"Swap image",
    alt_image:"Alternative image",
    mouseover:"for mouse over",
    mouseout:"for mouse out",
    misc:"Miscellaneous",
    example_img:"Appearance preview image",
    missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
    dialog_title:"Xoops Image Manager",
    src:"Image URL",
    alt:"Image description",
    list:"Image list",
    border:"Border",
    dimensions:"Dimensions",
    vspace:"Vertical space",
    hspace:"Horizontal space",
    align:"Alignment",
    align_baseline:"Baseline",
    align_top:"Top",
    align_middle:"Middle",
    align_bottom:"Bottom",
    align_texttop:"Text top",
    align_textbottom:"Text bottom",
    align_left:"Left",
    align_right:"Right",
    image_list:"Image list"
});

tinyMCE.addI18n('en.xoopsimagebrowser_dlg',{
    dialog_title:"Xoops Imagebrowser",
    tab_listimages:"Images",
    tab_loadimage:"Add image",
    tab_listcategories:"Categories",
    tab_createcategory:"Add category",
    select_image: "click on a image to select"
});
